import type { ContentPageDefinition } from '../../types';

/** Online Order page (#/menu). Keys prefixed `a_`/`b_`/`c_` belong to that Catalog layout only. */
export const catalogContent: ContentPageDefinition = {
  key: 'catalog',
  label: 'Online Order (Catalog)',
  description: 'The page where customers browse your items and add them to their order.',
  previewHash: '#/menu',
  module: 'catalog',
  groups: [
    // ---- Variant A - Menu Grid ----
    {
      id: 'a_header',
      title: 'Page header',
      description: 'The banner at the top of the order page.',
      variants: ['a'],
      fields: [
        { key: 'a_eyebrow', label: 'Small heading above the title', type: 'text' },
        { key: 'a_title', label: 'Title', type: 'text', hint: '{brand} is replaced with your business name.' },
        { key: 'a_rating', label: 'Rating', type: 'text' },
        { key: 'a_reviews', label: 'Reviews text', type: 'text' },
        { key: 'a_cuisine', label: 'Cuisine / style', type: 'text' },
        { key: 'a_prepTime', label: 'Preparation time', type: 'text' },
        { key: 'a_pickup', label: 'Pickup note', type: 'text' },
      ],
    },
    {
      id: 'a_sections',
      title: 'Menu sections',
      description: 'Headings of each section of the menu and the side menu of categories.',
      variants: ['a'],
      fields: [
        { key: 'a_popularHeading', label: 'Popular section heading', type: 'text' },
        { key: 'a_popularSubheading', label: 'Popular section side note', type: 'text' },
        { key: 'a_burgersHeading', label: 'Burgers & steaks section heading', type: 'text' },
        { key: 'a_burgersLink', label: 'Burgers & steaks section link', type: 'text' },
        { key: 'a_startersHeading', label: 'Starters & pizza section heading', type: 'text' },
        { key: 'a_dessertsHeading', label: 'Desserts & drinks section heading', type: 'text' },
        { key: 'a_sidebarTitle', label: 'Side menu title', type: 'text' },
        {
          key: 'a_sidebarCategories',
          label: 'Side menu categories',
          type: 'list',
          fixedItems: true,
          hint: 'Icon is a Material Symbols name, e.g. "local_pizza".',
          itemFields: [
            { key: 'label', label: 'Label', type: 'text' },
            { key: 'icon', label: 'Icon', type: 'text' },
          ],
        },
      ],
    },
    {
      id: 'a_filters',
      title: 'Search & filters',
      variants: ['a'],
      fields: [
        { key: 'a_searchPlaceholder', label: 'Search box placeholder', type: 'text' },
        { key: 'a_filterPopular', label: '"Popular" filter', type: 'text' },
        { key: 'a_filterVeg', label: '"Vegetarian" filter', type: 'text' },
        { key: 'a_filterNonVeg', label: '"Non-vegetarian" filter', type: 'text' },
        { key: 'a_emptyTitle', label: 'No results - title', type: 'text' },
        { key: 'a_emptyText', label: 'No results - message', type: 'text' },
        { key: 'a_cartTitle', label: 'Order bar title', type: 'text', hint: 'Shown at the bottom of the screen once something is in the order.' },
      ],
    },
    {
      id: 'a_labels',
      title: 'Buttons & messages',
      advanced: true,
      variants: ['a'],
      fields: [
        { key: 'a_addButton', label: 'Add button', type: 'text' },
        { key: 'a_addAnotherAria', label: '"Add another" button (screen readers)', type: 'text' },
        { key: 'a_shareButton', label: 'Share button', type: 'text' },
        { key: 'a_shareToast', label: 'Message after sharing', type: 'text' },
        { key: 'a_favoriteButton', label: 'Favorite button', type: 'text' },
        { key: 'a_favoritedButton', label: 'Favorite button (once favorited)', type: 'text' },
        { key: 'a_favoriteAddedToast', label: 'Message when added to favorites', type: 'text' },
        { key: 'a_favoriteRemovedToast', label: 'Message when removed from favorites', type: 'text' },
      ],
    },

    // ---- Variant B - Program Schedule ----
    {
      id: 'b_header',
      title: 'Page header & schedule',
      variants: ['b'],
      fields: [
        { key: 'b_eyebrow', label: 'Small heading above the title', type: 'text' },
        { key: 'b_title', label: 'Title', type: 'text' },
        { key: 'b_searchPlaceholder', label: 'Search box placeholder', type: 'text' },
        { key: 'b_cartTitle', label: 'Order bar title', type: 'text', hint: 'Shown at the bottom of the screen once something is selected.' },
      ],
    },
    {
      id: 'b_labels',
      title: 'Buttons & counts',
      advanced: true,
      variants: ['b'],
      fields: [
        { key: 'b_addButton', label: 'Book button', type: 'text' },
        { key: 'b_sessionCount', label: 'Number of sessions in a group', type: 'text', hint: '{count} is replaced with the number.' },
      ],
    },

    // ---- Variant C - Product List ----
    {
      id: 'c_header',
      title: 'Page header & list',
      variants: ['c'],
      fields: [
        { key: 'c_eyebrow', label: 'Small heading above the title', type: 'text' },
        { key: 'c_title', label: 'Title', type: 'text' },
        { key: 'c_searchPlaceholder', label: 'Search box placeholder', type: 'text' },
        { key: 'c_allCategories', label: '"All categories" option', type: 'text' },
        { key: 'c_emptyText', label: 'No results message', type: 'text' },
        { key: 'c_cartTitle', label: 'Order bar title', type: 'text', hint: 'Shown at the bottom of the screen once something is added.' },
      ],
    },
    {
      id: 'c_labels',
      title: 'Column headings & buttons',
      advanced: true,
      variants: ['c'],
      fields: [
        { key: 'c_colProduct', label: 'Product column', type: 'text' },
        { key: 'c_colCategory', label: 'Category column', type: 'text' },
        { key: 'c_colPrice', label: 'Price column', type: 'text' },
        { key: 'c_colQty', label: 'Quantity column', type: 'text' },
        { key: 'c_addButton', label: 'Add button', type: 'text' },
      ],
    },

    // ---- Shared by all layouts ----
    {
      id: 'orderBar',
      title: 'Order bar',
      description: 'The bar at the bottom of the screen showing what is in the order.',
      advanced: true,
      fields: [
        { key: 'checkoutButton', label: 'Checkout button', type: 'text' },
        { key: 'itemSingular', label: 'Item (one)', type: 'text' },
        { key: 'itemPlural', label: 'Items (several)', type: 'text' },
      ],
    },
  ],
  defaults: {
    // Variant A
    a_eyebrow: 'Fine Dining & Takeaway',
    a_title: '{brand}',
    a_rating: '4.9',
    a_reviews: '(2.4k+ Reviews)',
    a_cuisine: 'Modern French / Haute Cuisine',
    a_prepTime: '25-35 min',
    a_pickup: 'Pickup Available',
    a_popularHeading: 'Popular Choices',
    a_popularSubheading: 'Top rated by diners',
    a_burgersHeading: 'Burgers & Steaks',
    a_burgersLink: 'View Steaks',
    a_startersHeading: 'Starters & Pizza',
    a_dessertsHeading: 'Desserts & Fine Beverages',
    a_sidebarTitle: 'Categories',
    a_sidebarCategories: [
      { id: 'popular', label: 'Popular', icon: 'star' },
      { id: 'burgers', label: 'Burgers', icon: 'lunch_dining' },
      { id: 'starters', label: 'Starters', icon: 'restaurant' },
      { id: 'pizza', label: 'Pizza', icon: 'local_pizza' },
      { id: 'pasta', label: 'Pasta', icon: 'dinner_dining' },
      { id: 'steaks', label: 'Steaks', icon: 'flatware' },
      { id: 'desserts', label: 'Desserts', icon: 'icecream' },
      { id: 'beverages', label: 'Beverages', icon: 'local_bar' },
    ],
    a_searchPlaceholder: 'Search for dishes, drinks, or ingredients...',
    a_filterPopular: 'Popular',
    a_filterVeg: 'Veg',
    a_filterNonVeg: 'Non-Veg',
    a_emptyTitle: 'No dishes found',
    a_emptyText: 'Try adjusting your search query or filter selection.',
    a_cartTitle: 'Selected Gourmet Order',
    a_addButton: 'ADD',
    a_addAnotherAria: 'Add another with options',
    a_shareButton: 'Share',
    a_shareToast: 'Menu link copied to clipboard!',
    a_favoriteButton: 'Favorite',
    a_favoritedButton: 'Favorited',
    a_favoriteAddedToast: 'Added to favorites',
    a_favoriteRemovedToast: 'Removed from favorites',
    // Variant B
    b_eyebrow: 'Weekly Schedule',
    b_title: 'Programs',
    b_searchPlaceholder: 'Search programs...',
    b_cartTitle: 'Selected Sessions',
    b_addButton: 'Book',
    b_sessionCount: '{count} sessions',
    // Variant C
    c_eyebrow: 'Shop',
    c_title: 'Products',
    c_searchPlaceholder: 'Search products...',
    c_allCategories: 'All categories',
    c_emptyText: 'No products match your search.',
    c_cartTitle: 'Cart',
    c_colProduct: 'Product',
    c_colCategory: 'Category',
    c_colPrice: 'Price',
    c_colQty: 'Qty',
    c_addButton: 'Add',
    // Shared
    checkoutButton: 'Checkout',
    itemSingular: 'Item',
    itemPlural: 'Items',
  },
};
